class Orderbooks:
    MARKET = 'market'
    ID = 'id'
    ISIN = 'isin'
    LAST_TRADING_DATE = 'last_trading_date'
    SIZE = 'size'
    TIME = 'time'
    CLOSE = 'close'
    LOW = 'low'
    HIGH = 'high'
    INITIAL_MARGIN = 'initial_margin'
    LAST_PRICE = 'last_price'
    YESTERDAY_PRICE = 'yesterday_price'
    BIDS = 'bids'
    ASKS = 'asks'
    EVENT_TYPE = 'event_type'
